#:kivy 1.0.9

####################
# SETTING CONSTANT #
####################

#:set DashboardScreenName 'Dashboard'
#:set TransactionScreenName 'Transaction'
#:set ETFETCScreenName 'ETF-ETC'
#:set StocksScreenName 'Stock'
#:set BondScreenName 'Bond'
#:set CommodityScreenName 'Commodities'
#:set CryptoScreenName 'Crypto'
#:set StatisticsScreenName 'Statistics'
#:set SettingScreenName 'Setting'

#:set ButtonMenu_size_hint_y 0.07
#:set ButtonMenu_size_hint_x 1