#:kivy 1.0.9

<Widgets>:
    Button:
        text: "Press me"
        on_release: root.btn()

<P>:
    Label:
        text: "You pressed the button"
        size_hint: 0.6, 0.2
        pos_hint: {"x":0.2, "top":1}

    Button:
        text: "You pressed the button"
        size_hint: 0.8, 0.2
        pos_hint: {"x":0.1, "y":0.1}

# Button used for the swap of screens
<CustomTransactionMenuSquareButton>:
    id: ButtonToPress
    font_name: app.Configuration.GetElementValue('ProfileNameFontName')
    font_size: app.Configuration.GetElementValue('ProfileNameFontSize')
    background_color: app.Configuration.GetElementValue('TransparentBackgroundColor') 
    canvas.before:
        Color:
            rgba: root.BackgroundColor
        RoundedRectangle:
            pos: self.pos
            size: self.size

<CustomDateFeeDateSquareButton>:
    id: DateFeeNoteButton
    font_name: app.Configuration.GetElementValue('ProfileNameFontName')
    font_size: app.Configuration.GetElementValue('ProfileNameFontSize')
    background_color: app.Configuration.GetElementValue('TransparentBackgroundColor') 
    canvas.before:
        Color:
            rgba: root.BackgroundColor
        RoundedRectangle:
            pos: self.pos
            size: self.size


<BuySellScreen>:
    name: app.Configuration.GetElementValue('AssetTransactionPopupScreenDictionary')["BUY"] 

    BoxLayout:
        orientation: 'vertical'
        padding: ("10dp","10dp","10dp","10dp")

        canvas:
            Color:
                rgba: 0.3,0.3,0.3,0.7
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [(10, 10), (10, 10), (10, 10), (10, 10)]

        # Buying Section
        BoxLayout:
            id: BuyingSectionBody
            orientation: 'vertical'
            size_hint: 1, 1
            spacing: "10dp"

            # Box Layout containg Asset, Account ect
            BoxLayout:
                id: AssetSymbolBoxLayout
                size_hint: 1, 0.75
                orientation: 'vertical'
                padding: ("15dp","0dp","15dp","10dp")
                
                # Asset and Symbol BoxLayout
                BoxLayout: 
                    orientation: 'horizontal'
                    size_hint: 1, 0.33

                    # Asset BoxLayout
                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.5, 1
                        padding: ("0dp","2dp","0dp","5dp")

                        Label:
                            text: 'Asset'
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                        TextInput: 
                            id: AssetValue
                            readonly : True
                            size_hint: 0.6, 1
                            pos_hint: {'x': 0.2}
                            multiline: 0
                            background_color: 0.1,0.1,0.1,0.7
                            foreground_color: 1,1,1,1
                            cursor_color: 1,1,1,1
                            font_name: app.Configuration.GetElementValue('PopupTitleFontName')
                            font_size: app.Configuration.GetElementValue('PopupTextFieldFontSize')
                            halign: 'center'

                    # Symbol BoxLayout
                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.5, 1
                        padding: ("0dp","2dp","0dp","5dp")

                        Label:
                            text: 'Symbol'
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                        TextInput: 
                            id: SymbolValue
                            readonly : True
                            size_hint: 0.6, 1
                            pos_hint: {'x': 0.2}
                            multiline: 0
                            background_color: 0.1,0.1,0.1,0.7
                            foreground_color: 1,1,1,1
                            cursor_color: 1,1,1,1
                            font_name: app.Configuration.GetElementValue('PopupTitleFontName')
                            font_size: app.Configuration.GetElementValue('PopupTextFieldFontSize')
                            halign: 'center'
                                            
                # Quantity and Price per coin box layout
                BoxLayout: 
                    orientation: 'horizontal'
                    size_hint: 1, 0.33

                    # Quantity BoxLayout
                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.5, 1
                        padding: ("0dp","2dp","0dp","5dp")

                        Label:
                            text: 'Quantity'
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                        TextInput: 
                            id: QuantityValue
                            on_text: root.compute_value_spent()
                            size_hint: 0.6, 1
                            pos_hint: {'x': 0.2, 'y': - 0.25}
                            text: '0.0'
                            multiline: 0
                            background_color: 0.1,0.1,0.1,0.7
                            foreground_color: 1,1,1,1
                            cursor_color: 1,1,1,1
                            font_name: app.Configuration.GetElementValue('PopupTitleFontName')
                            font_size: app.Configuration.GetElementValue('PopupTextFieldFontSize')
                            halign: 'center'
                            valign: 'center'


                    # Price per Coin BoxLayout
                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.5, 1
                        padding: ("0dp","2dp","0dp","5dp")

                        Label:
                            id: PricePerCoinStr
                            text: 'Price Per Coin'
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                        TextInput: 
                            id: PricePerCoinValue
                            on_text: root.compute_value_spent()
                            size_hint: 0.6, 1
                            pos_hint: {'x': 0.2}
                            multiline: 0
                            background_color: 0.1,0.1,0.1,0.7
                            foreground_color: 1,1,1,1
                            cursor_color: 1,1,1,1
                            font_name: app.Configuration.GetElementValue('PopupTitleFontName')
                            font_size: app.Configuration.GetElementValue('PopupTextFieldFontSize')
                            halign: 'center'

                # Paying with and storing box layout
                BoxLayout: 
                    orientation: 'horizontal'
                    size_hint: 1, 0.33

                    # Paying with BoxLayout
                    BoxLayout:
                        id: PayingAccountBoxLayout
                        orientation: 'vertical'
                        size_hint: 0.5, 1
                        padding: ("0dp","2dp","0dp","5dp")

                        Label:
                            text: 'Paying Account'
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                        Button:
                            text: 'Open Select account'
                            on_release: root.open_select_account_popup()
                    
                    # Storing Box Layout
                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.5, 1
                        padding: ("0dp","2dp","0dp","5dp")

                        Label:
                            text: 'Storing Account'
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                        TextInput: 
                            id: StoringAccountValue
                            readonly : True
                            multiline: 0
                            size_hint: 0.6, 1
                            pos_hint: {'x': 0.2}
                            background_color: 0.1,0.1,0.1,0.7
                            foreground_color: 1,1,1,1
                            cursor_color: 1,1,1,1
                            font_name: app.Configuration.GetElementValue('PopupTitleFontName')
                            font_size: app.Configuration.GetElementValue('PopupTextFieldFontSize')
                            halign: 'center'

            # Box Containg date buttons, fees and notes
            BoxLayout:
                id: DateFeeNoteButtonsBoxLayout
                size_hint: 1, 0.125
                orientation: 'horizontal' 
                spacing: "10dp"

                # Date Picker
                RelativeLayout:
                    size_hint: 0.25, 1

                    CustomDateFeeDateSquareButton:
                        on_release: self.show_date_picker(root.parent.parent.parent.date)
                        
                    # Date Button
                    BoxLayout:
                        id: DateBoxLayoutButton
                        orientation: 'horizontal'
                        background_color: app.Configuration.GetElementValue('TransparentBackgroundColor') 
                        spacing: "0dp"
                        padding: ("10dp","0dp","10dp","0dp")

                        BoxLayout:
                            size_hint: 0.25, 1

                            Image:
                                size_hint: 0.5, 0.5
                                pos_hint: {'x' : 0.25, 'y' : 0.25}
                                id: ButtonImage
                                size:  self.size
                                source: './images/button/Date.png'

                        Label:
                            id: DateTextstr
                            text: '20 August 2022'
                            size_hint: 0.75, 1
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                # Fee Button
                RelativeLayout:
                    size_hint: 0.175, 1

                    CustomDateFeeDateSquareButton:
                        on_release: self.OpeningAddFee(root.parent.parent.parent.fee)
                    
                    BoxLayout:
                        id: FeeBoxLayoutButton
                        orientation: 'horizontal'
                        background_color: app.Configuration.GetElementValue('TransparentBackgroundColor') 
                        spacing: "0dp"
                        padding: ("10dp","0dp","10dp","0dp")

                        BoxLayout:
                            size_hint: 0.3, 1

                            Image:
                                size_hint: 0.5, 0.5
                                pos_hint: {'x' : 0.25, 'y' : 0.25}
                                id: ButtonImage
                                size:  self.size
                                source: './images/button/Fee.png'

                        Label:
                            text: 'Add fee'
                            size_hint: 0.7, 1
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20

                # Note Button
                RelativeLayout:
                    size_hint: 0.175, 1

                    CustomDateFeeDateSquareButton:
                        on_release: self.OpeningAddNote(root.parent.parent.parent.note)
                    
                    BoxLayout:
                        id: NoteBoxLayoutButton
                        orientation: 'horizontal'
                        background_color: app.Configuration.GetElementValue('TransparentBackgroundColor') 
                        spacing: "0dp"
                        padding: ("10dp","0dp","10dp","0dp")

                        BoxLayout:
                            size_hint: 0.3, 1

                            Image:
                                size_hint: 0.5, 0.5
                                pos_hint: {'x' : 0.25, 'y' : 0.25}
                                id: ButtonImage
                                size:  self.size
                                source: './images/button/Note.png'

                        Label:
                            text: 'Add note'
                            size_hint: 0.7, 1
                            text_size: self.width, None
                            size: self.texture_size
                            font_name: 'Candarab'
                            halign: 'center'
                            font_size: 20    
                
            # TotalSpent Canvas
            BoxLayout:
                id: TotalSpentBoxLayoutButton
                orientation: 'horizontal'
                size_hint: 1, 0.125
                background_color: app.Configuration.GetElementValue('TransparentBackgroundColor') 
                spacing: "0dp"
                padding: ("10dp","0dp","10dp","0dp")

                canvas:
                    Color:
                        rgba: 0.1,0.1,0.1,0.7
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size

                Label:
                    id: TotalSpentLabel
                    text: 'Total Spent: $'
                    size_hint: 0.35, 1
                    text_size: self.width, None
                    size: self.texture_size
                    font_name: 'Candarab'
                    halign: 'center'
                    font_size: 20
                
                Label:
                    id: TotalSpentValue
                    text: '0.00'
                    size_hint: 0.65, 1
                    text_size: self.width, None
                    size: self.texture_size
                    font_name: 'Candarab'
                    halign: 'center'
                    font_size: 25            
            
<SwapScreen>:
    name: app.Configuration.GetElementValue('AssetTransactionPopupScreenDictionary')["SWAP"] 
    Label:
        text: 'SwapScreen'

<AddAssetTransactionPopup>:
    background_color: 0,0,0,0
    
    # Canvas for the poup background background
    canvas.before:
        Color:
            rgba: 0.5,0.5,0.5,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(10, 10), (10, 10), (10, 10), (10, 10)]
    
    # Main Box Layout
    BoxLayout:
        orientation: 'vertical'
        padding: ("30dp","30dp","30dp","30dp")
        spacing: "20dp"

        # First row with title and X button - y: 0.075
        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, 0.075

            BoxLayout:
                id: CanvasLabelIdentifier
                orientation: 'horizontal'

                Label:
                    text: root.title
                    text_size: self.width, None
                    size: self.texture_size
                    halign: 'center'
                    font_name: 'Candarab'
                    font_size: 25
    
        # Popup of button to select a Screen - y: 0.075
        BoxLayout:
            orientation: 'vertical'
            padding: ("80dp","0dp","80dp","0dp")
            size_hint: 1, 0.075

            BoxLayout:
                id: BuySellSwapButtons
                orientation: 'horizontal'
                size_hint: 1, 0.5
                padding: ("5dp","5dp","5dp","5dp")
                spacing: "15dp"

                canvas.before:
                    Color:
                        rgba: 0.3,0.3,0.3,0.7
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [(10, 10), (10, 10), (10, 10), (10, 10)]

                CustomTransactionMenuSquareButton:
                    id: BUY_BTN
                    text: 'BUY'
                    on_release: self.move_transaction_screen(root)

                CustomTransactionMenuSquareButton:
                    id: SELL_BTN
                    text: 'SELL'
                    on_release: self.move_transaction_screen(root)
                
                CustomTransactionMenuSquareButton:
                    id: SWAP_BTN
                    text: 'SWAP'
                    on_release: self.move_transaction_screen(root)

        # Screen Containg the action according to the user push - y : 0.75
        ScreenManager:
            id: ScreenManagerSection
            size_hint: 1, 0.75

            BuySellScreen:
            SwapScreen:
                
        # Box Layout containg the Confirmation button - y : 0.1
        BoxLayout:
            orientation: 'horizontal'
            spacing: "10dp"
            size_hint: 1, 0.1
            pos_hint: {'x': 0, 'y': 1}

            Button:
                background_color: 0,0,0,0
                canvas.before:
                    Color:
                        rgba: 0.1,0.1,0.9,0.7
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [(10, 10), (10, 10), (10, 10), (10, 10)]

                id: Confirm
                font_name: app.Configuration.GetElementValue('PopupTitleFontName')
                font_size: app.Configuration.GetElementValue('PopupInnerFontSize')
                text:'Add Transaction'
                on_release: root.AddTransaction(app)

            Button:
                background_color: 0,0,0,0
                canvas.before:
                    Color:
                        rgba: 0.9,0.1,0.1,0.7
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [(10, 10), (10, 10), (10, 10), (10, 10)]

                id: Cancel
                font_name: app.Configuration.GetElementValue('PopupTitleFontName')
                font_size: app.Configuration.GetElementValue('PopupInnerFontSize')
                text:'Cancel'
                on_release: root.Cancel()
